CLOUD_DEPLOY_FILEPATH="scripts/gcf_deploy.yaml"
SUBSTITUTIONS_DEPLOY="_SERVICE_REGION=$SERVICE_REGION,_GCF_NAME=$GCF_NAME,_GCF_SERVICE_ACCOUNT=$GCF_SAC_EMAIL,_PUBSUB_TOPIC=$PUBSUB_TOPIC,_PROJECT_ID=$PROJECT_ID,_SENDGRID_API_KEY=$SENDGRID_API_KEY,_FROM=$FROM,_TO=$TO"
gcloud builds submit --config $CLOUD_DEPLOY_FILEPATH --project $PROJECT_ID --substitutions "$SUBSTITUTIONS_DEPLOY"
